import type { GameMeta } from './types'

export const GAMES: GameMeta[] = [
  // ---- Arcade ----
  { id: 'snake', name: 'Snake', emoji: '🐍', category: 'arcade', color: 'lime', scoreLabel: 'apples', ready: true,
    howTo: 'Swipe or use arrow keys to steer the snake. Eat apples to grow. Don’t bump into yourself!',
    load: () => import('./snake/SnakeGame') },
  { id: 'tictactoe', name: 'Tic-Tac-Toe', emoji: '🐱', category: 'arcade', color: 'sky', scoreLabel: 'wins', ready: true,
    howTo: 'Get three in a row! Cats go first. Play against the robot or a friend on the same screen.',
    load: () => import('./tictactoe/TicTacToeGame') },
  { id: 'memory', name: 'Memory Match', emoji: '🦊', category: 'arcade', color: 'grape', scoreLabel: 'pairs', ready: true,
    howTo: 'Flip two cards. If they match, they stay open. Find every pair in as few flips as you can.',
    load: () => import('./memory/MemoryGame') },
  { id: 'brainvita', name: 'Brainvita', emoji: '💎', category: 'arcade', color: 'sun', scoreLabel: 'cleared', ready: true,
    howTo: 'Tap a gem, then tap an empty hole to jump over a neighbour. Jumped gems disappear. Try to leave just one!',
    load: () => import('./brainvita/BrainvitaGame') },
  { id: 'bubblepop', name: 'Bubble Pop', emoji: '🫧', category: 'arcade', color: 'sky', scoreLabel: 'bubbles', ready: true,
    howTo: 'Drag to aim, let go to fire. Match three or more of the same colour to pop them. Don’t let the bubbles reach the bottom!',
    load: () => import('./bubblepop/BubblePopGame') },
  { id: 'kartdash', name: 'Kart Dash', emoji: '🏎️', category: 'arcade', color: 'orange', scoreLabel: 'stars', ready: true,
    howTo: 'Tap the left or right side (or swipe / arrow keys) to change lanes. Collect stars, dodge puddles — they only slow you down!',
    load: () => import('./kartdash/KartDashGame') },
  { id: 'whack', name: 'Whack-a-Mole', emoji: '🐹', category: 'arcade', color: 'pink', scoreLabel: 'moles', ready: true,
    howTo: 'Moles pop out of the holes — tap them before they hide! 30 seconds, go go go!',
    load: () => import('./whack/WhackGame') },
  { id: 'bricks', name: 'Brick Breaker', emoji: '🧱', category: 'arcade', color: 'orange', scoreLabel: 'bricks', ready: true,
    howTo: 'Slide your finger (or use arrow keys) to move the paddle. Bounce the ball and smash every brick!',
    load: () => import('./bricks/BricksGame') },
  { id: 'fruitcatch', name: 'Fruit Catch', emoji: '🍉', category: 'arcade', color: 'lime', scoreLabel: 'fruit', ready: true,
    howTo: 'Slide your finger (or use arrow keys) to move the basket. Catch the fruit, but watch out for boots — three boots and the round ends!',
    load: () => import('./fruitcatch/FruitCatchGame') },
  { id: 'flappy', name: 'Flappy Bee', emoji: '🐝', category: 'arcade', color: 'sun', scoreLabel: 'flowers', ready: true,
    howTo: 'Tap (or press space) to flap. Fly the bee through the gaps between the flowers. Short rounds — just try again!',
    load: () => import('./flappy/FlappyGame') },
  { id: 'connect4', name: 'Connect Four', emoji: '🔴', category: 'arcade', color: 'pink', scoreLabel: 'wins', ready: true,
    howTo: 'Tap a column to drop your disc. First to get four in a row — across, down or diagonal — wins!',
    load: () => import('./connect4/ConnectFourGame') },
  { id: 'simon', name: 'Colour Echo', emoji: '🎵', category: 'arcade', color: 'grape', scoreLabel: 'rounds', ready: true,
    howTo: 'Watch and listen as the colours light up, then tap them back in the same order. Each round adds one more!',
    load: () => import('./simon/SimonGame') },
  // ---- Brain Gym ----
  { id: 'sudoku', name: 'Sudoku Jr.', emoji: '🍓', category: 'brain', color: 'pink', scoreLabel: 'solved', ready: true,
    howTo: 'Fill the grid so every row, column and box has each picture exactly once. Tap a square, then tap a picture.',
    load: () => import('@/brain-gym/sudoku/SudokuGame') },
  { id: 'maze', name: 'Maze Runner', emoji: '⭐', category: 'brain', color: 'sun', scoreLabel: 'stars', ready: true,
    howTo: 'Guide the bunny through the maze to the star. Swipe, use arrows or the D-pad.',
    load: () => import('@/brain-gym/maze/MazeGame') },
  { id: 'spot', name: 'Spot the Difference', emoji: '🔍', category: 'brain', color: 'sky', scoreLabel: 'found', ready: true,
    howTo: 'Two pictures look the same… but a few things changed! Tap each difference in either picture.',
    load: () => import('@/brain-gym/spot/SpotGame') },
  { id: 'pattern', name: 'What Comes Next?', emoji: '🔺', category: 'brain', color: 'orange', scoreLabel: 'right', ready: true,
    howTo: 'Look at the pattern. What comes next? Tap the right answer. 8 rounds!',
    load: () => import('@/brain-gym/pattern/PatternGame') },
  { id: 'oddone', name: 'Odd One Out', emoji: '🦆', category: 'brain', color: 'lime', scoreLabel: 'right', ready: true,
    howTo: 'One of these doesn’t belong with the others. Tap the odd one out! 8 rounds.',
    load: () => import('@/brain-gym/oddone/OddOneGame') },
  { id: 'slider', name: 'Sliding Puzzle', emoji: '🧩', category: 'brain', color: 'grape', scoreLabel: 'solved', ready: true,
    howTo: 'Tap a tile next to the empty space to slide it. Put the picture back together!',
    load: () => import('@/brain-gym/slider/SliderGame') },
  { id: 'quickmaths', name: 'Quick Maths', emoji: '➕', category: 'brain', color: 'sun', scoreLabel: 'correct', ready: true,
    howTo: '10 sums — tap the right answer. Easy has no timer; Normal and Hard give you 10 seconds each.',
    load: () => import('@/brain-gym/quickmaths/QuickMathsGame') },
  { id: 'tangram', name: 'Tangram', emoji: '🔷', category: 'brain', color: 'sky', scoreLabel: 'pieces', ready: true,
    howTo: 'Drag each shape from the bottom onto the grey picture until it clicks into place. Fill the whole shape!',
    load: () => import('@/brain-gym/tangram/TangramGame') },
  // ---- Brain Lab (teens 14+) ----
  { id: 'g2048', name: '2048', emoji: '🔢', category: 'teen', color: 'sun', scoreLabel: 'points', ready: true,
    howTo: 'Swipe or use arrow keys to slide all tiles. Tiles with the same number merge. Reach 2048 — then keep going for a high score!',
    load: () => import('@/brain-lab/g2048/Game2048') },
  { id: 'minesweeper', name: 'Minesweeper', emoji: '💣', category: 'teen', color: 'grape', scoreLabel: 'cleared', ready: true,
    howTo: 'Tap to reveal a square; the number says how many mines touch it. Use the 🚩 button (or long-press) to flag mines. Clear every safe square!',
    load: () => import('@/brain-lab/minesweeper/MinesweeperGame') },
  { id: 'wordguess', name: 'Word Guess', emoji: '🔤', category: 'teen', color: 'lime', scoreLabel: 'points', ready: true,
    howTo: 'Guess the 5-letter word. Green = right letter, right place. Yellow = right letter, wrong place. Grey = not in the word.',
    load: () => import('@/brain-lab/wordguess/WordGuessGame') },
  { id: 'codebreaker', name: 'Code Breaker', emoji: '🕵️', category: 'teen', color: 'sky', scoreLabel: 'points', ready: true,
    howTo: 'Crack the secret colour code. After each guess: ⚫ = right colour in the right spot, ⚪ = right colour, wrong spot. Deduce it before your guesses run out!',
    load: () => import('@/brain-lab/codebreaker/CodeBreakerGame') },
  { id: 'lightsout', name: 'Lights Out', emoji: '💡', category: 'teen', color: 'orange', scoreLabel: 'solved', ready: true,
    howTo: 'Tapping a light toggles it and its four neighbours. Turn every light off in as few moves as you can.',
    load: () => import('@/brain-lab/lightsout/LightsOutGame') },
]

export const getGame = (id: string) => GAMES.find((g) => g.id === id)