import type { GameMeta } from './types'

export const GAMES: GameMeta[] = [
  // ---- Arcade ----
  { id: 'snake', name: 'Snake', emoji: '🐍', category: 'arcade', color: 'lime', scoreLabel: 'apples', ready: true,
    howTo: 'Swipe or use arrow keys to steer the snake. Eat apples to grow. Don’t bump into yourself!',
    load: () => import('./snake/SnakeGame') },
  { id: 'tictactoe', name: 'Tic-Tac-Toe', emoji: '🐱', category: 'arcade', color: 'sky', scoreLabel: 'wins', ready: true,
    howTo: 'Get three in a row! Cats go first. Play against the robot or a friend on the same screen.',
    load: () => import('./tictactoe/TicTacToeGame') },
  { id: 'memory', name: 'Memory Match', emoji: '🦊', category: 'arcade', color: 'grape', scoreLabel: 'pairs', ready: true,
    howTo: 'Flip two cards. If they match, they stay open. Find every pair in as few flips as you can.',
    load: () => import('./memory/MemoryGame') },
  { id: 'brainvita', name: 'Brainvita', emoji: '💎', category: 'arcade', color: 'sun', scoreLabel: 'gems left', ready: false,
    howTo: 'Jump one gem over another into an empty hole. Try to leave just one gem!' },
  { id: 'bubblepop', name: 'Bubble Pop', emoji: '🫧', category: 'arcade', color: 'sky', scoreLabel: 'bubbles', ready: false,
    howTo: 'Aim and fire bubbles. Match three of the same colour to pop them.' },
  { id: 'kartdash', name: 'Kart Dash', emoji: '🏎️', category: 'arcade', color: 'orange', scoreLabel: 'stars', ready: false,
    howTo: 'Swipe left and right to change lanes. Collect stars, dodge puddles!' },
  { id: 'whack', name: 'Whack-a-Mole', emoji: '🐹', category: 'arcade', color: 'pink', scoreLabel: 'moles', ready: false,
    howTo: 'Tap the moles as they pop up. Quick!' },
  { id: 'bricks', name: 'Brick Breaker', emoji: '🧱', category: 'arcade', color: 'orange', scoreLabel: 'bricks', ready: false,
    howTo: 'Move the paddle to bounce the ball and break all the bricks.' },
  { id: 'fruitcatch', name: 'Fruit Catch', emoji: '🍉', category: 'arcade', color: 'lime', scoreLabel: 'fruit', ready: false,
    howTo: 'Move the basket to catch falling fruit. Dodge the boots!' },
  { id: 'flappy', name: 'Flappy Bee', emoji: '🐝', category: 'arcade', color: 'sun', scoreLabel: 'flowers', ready: false,
    howTo: 'Tap to flap. Fly through the flower gaps.' },
  { id: 'connect4', name: 'Connect Four', emoji: '🔴', category: 'arcade', color: 'pink', scoreLabel: 'wins', ready: false,
    howTo: 'Drop discs into the grid. Four in a row wins!' },
  { id: 'simon', name: 'Colour Echo', emoji: '🎵', category: 'arcade', color: 'grape', scoreLabel: 'rounds', ready: false,
    howTo: 'Watch the colours light up, then repeat the pattern.' },
  // ---- Brain Gym ----
  { id: 'sudoku', name: 'Sudoku Jr.', emoji: '🍓', category: 'brain', color: 'pink', scoreLabel: 'solved', ready: true,
    howTo: 'Fill the grid so every row, column and box has each picture exactly once. Tap a square, then tap a picture.',
    load: () => import('@/brain-gym/sudoku/SudokuGame') },
  { id: 'maze', name: 'Maze Runner', emoji: '⭐', category: 'brain', color: 'sun', scoreLabel: 'stars', ready: true,
    howTo: 'Guide the bunny through the maze to the star. Swipe, use arrows or the D-pad.',
    load: () => import('@/brain-gym/maze/MazeGame') },
  { id: 'spot', name: 'Spot the Difference', emoji: '🔍', category: 'brain', color: 'sky', scoreLabel: 'found', ready: false,
    howTo: 'Two pictures, five differences. Tap them all!' },
  { id: 'pattern', name: 'What Comes Next?', emoji: '🔺', category: 'brain', color: 'orange', scoreLabel: 'solved', ready: false,
    howTo: 'Look at the pattern and pick the shape that comes next.' },
  { id: 'oddone', name: 'Odd One Out', emoji: '🦆', category: 'brain', color: 'lime', scoreLabel: 'solved', ready: false,
    howTo: 'One of these is not like the others. Tap it!' },
  { id: 'slider', name: 'Sliding Puzzle', emoji: '🧩', category: 'brain', color: 'grape', scoreLabel: 'solved', ready: false,
    howTo: 'Slide the tiles to put the picture back together.' },
  { id: 'quickmaths', name: 'Quick Maths', emoji: '➕', category: 'brain', color: 'sun', scoreLabel: 'correct', ready: false,
    howTo: 'Answer as many sums as you can. Pick the right number!' },
  { id: 'tangram', name: 'Tangram', emoji: '🔷', category: 'brain', color: 'sky', scoreLabel: 'solved', ready: false,
    howTo: 'Drag the shapes to fill the picture.' },
]

export const getGame = (id: string) => GAMES.find((g) => g.id === id)
